--Пример "грязного" чтения 2 часть
USE Airport

/*
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
BEGIN TRANSACTION

SELECT Flight.Overweight FROM Flight
WHERE Flight_ID = 5
COMMIT
*/

SET TRANSACTION ISOLATION LEVEL READ COMMITTED
BEGIN TRANSACTION
SELECT Flight.Overweight FROM Flight
WHERE Flight_ID = 5
COMMIT