USE Airport

DROP USER s33
DROP LOGIN d33;

DROP TABLE Alphabet
DROP TABLE No_Alphabet
DROP TABLE WhySuchAStrangeNameForATable

CREATE LOGIN d33 WITH PASSWORD = 'd33' 
CREATE USER s33 FOR LOGIN d33

GRANT CREATE TABLE TO s33;

GRANT ALTER ON SCHEMA::dbo TO s33;

--EXECUTE AS USER = 's33'
EXECUTE AS LOGIN = 'd33'
CREATE TABLE Alphabet(
	Number INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	Letter VARCHAR(5) NOT NULL);
CREATE TABLE No_Alphabet(
	Number INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	Letter VARCHAR(5) NOT NULL);
CREATE TABLE WhySuchAStrangeNameForATable(
	Number INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	Letter VARCHAR(5) NOT NULL);

REVERT


--SELECT * FROM sys.database_principals

GRANT SELECT ON SCHEMA::dbo TO s33;

EXECUTE AS USER = 's33'
SELECT * FROM Timetable;
REVERT

/*
INSERT INTO Alphabet VALUES ('A');
INSERT INTO Alphabet VALUES ('B');
INSERT INTO Alphabet VALUES ('C');
INSERT INTO Alphabet VALUES ('D');
INSERT INTO Alphabet VALUES ('E');
INSERT INTO Alphabet VALUES ('F');
INSERT INTO Alphabet VALUES ('G');
INSERT INTO Alphabet VALUES ('H');
INSERT INTO Alphabet VALUES ('I');
INSERT INTO Alphabet VALUES ('J');
INSERT INTO Alphabet VALUES ('K');
INSERT INTO Alphabet VALUES ('L');
INSERT INTO Alphabet VALUES ('M');
INSERT INTO Alphabet VALUES ('O');
INSERT INTO Alphabet VALUES ('P');
INSERT INTO Alphabet VALUES ('Q');
INSERT INTO Alphabet VALUES ('R');
INSERT INTO Alphabet VALUES ('S');
INSERT INTO Alphabet VALUES ('T');
INSERT INTO Alphabet VALUES ('U');
INSERT INTO Alphabet VALUES ('V');
INSERT INTO Alphabet VALUES ('W');
INSERT INTO Alphabet VALUES ('X');
INSERT INTO Alphabet VALUES ('Y');
INSERT INTO Alphabet VALUES ('Z');
*/